# SPDX-FileCopyrightText: 2025 Elwan Mayencourt <mayencourt@elwan.ch>
#
# SPDX-License-Identifier: MIT

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

universal_binaries:
  - replace: false

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - maintainer: Elwan Mayencourt <mayencourt@elwan.ch>
    description: A dumb Redis-compatible key-value database using Docker as storage
    homepage: https://github.com/Bogorg/kvd
    license: MIT
    formats:
      - deb
      - rpm
      - apk

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  mode: keep-existing
