# SPDX-FileCopyrightText: 2025 Elwan Mayencourt <mayencourt@elwan.ch>
#
# SPDX-License-Identifier: MIT

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kvd-windows
    main: ./cmd/kvd
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}

archives:
  - id: winzip
    format: zip
    name_template: >-
      {{ .ProjectName }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  mode: keep-existing
  draft: false
  prerelease: auto

chocolateys:
  - name: kvd
    ids: [winzip]
    title: "KVD - Docker-based Redis-compatible key-value database"
    url_template: "https://github.com/{{ .RepoOwner }}/{{ .RepoName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    owners: "Elwan Mayencourt"
    authors: "Elwan Mayencourt"
    project_url: "https://github.com/YungBricoCoop/kvd"
    project_source_url: "https://github.com/YungBricoCoop/kvd"
    docs_url: "https://github.com/YungBricoCoop/kvd/blob/main/README.md"
    bug_tracker_url: "https://github.com/YungBricoCoop/kvd/issues"
    license_url: "https://github.com/YungBricoCoop/kvd/blob/main/LICENSE"
    require_license_acceptance: false
    tags: "redis docker key-value database cli"
    summary: "A dumb Redis-compatible key-value database using Docker as storage"
    description: |
      KVD is a deliberately inefficient but fun key-value database that uses
      Docker containers as its storage engine. It speaks the RESP protocol,
      making it compatible with Redis clients and commands.
    release_notes: "https://github.com/YungBricoCoop/kvd/releases/tag/{{ .Tag }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    skip_publish: false
    version_template: "{{ trimPrefix .VersionPrefix .Version }}"
